### ISSUE TITLE
Trong - BE: User register

### ISSUE THREAD

**Issue by UpperMoon0** [KhoaAii/Diamond-Shop-System-SWP391-SE1840-Group6#15]
Implement the register method.
Use the register branch on github.

Note:
- You have to config the database correctly or it won't run. Ask me in case you don't know.

Requirements:
- You should only edit the code in the register method of the AuthController class. (In the BE project, go to src/main/java/vn/fpt/diamond_shop/controller/AuthController).
- The method should check for existing emails, if a user already have the registered email, throw a BadRequestException.
- The password must be encoded before being saved to the database, use the passwordEncoder object in the class.
- After saving to the database, the method should return a response with the status code 200 ok.
- Your method must pass both test cases before commit.

How to test:
- In the BE project, go to src/test/java/vn/fpt/diamond_shop/controller/AuthControllerTest.
- In the AuthControllerTest class, run the tests (or use the shortcut Ctrl+Shift+F10 if you are using IntelliJ).
- If both tests pass, your method is correct, if one fails, your method is not correct.

**Comment by ToLazyToCode** [comment]
Done!

**Comment by UpperMoon0** [comment]
Good job
